name: stavnica
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.18.1 <3.0.0'

dependencies:
  auto_route: ^5.0.4
  cloud_firestore: ^4.1.0
  cupertino_icons: ^1.0.2
  firebase_auth: ^4.1.4
  firebase_core: ^2.3.0
  flow_builder: ^0.0.9
  flutter:
    sdk: flutter
  flutter_login: ^4.1.0
  flutter_riverpod: ^2.1.1
  freezed_annotation: ^2.2.0
  get_it: ^7.2.0
  injectable: ^2.0.1
  lottie: ^2.0.0
  oxidized: ^5.2.0
  riverpod_annotation: ^1.0.6
  salomon_bottom_bar: ^3.3.1
  tuple: ^2.0.1

dev_dependencies:
  auto_route_generator: ^5.0.3
  build_runner: ^2.3.2
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  freezed: ^2.2.1
  injectable_generator: ^2.0.1
  json_serializable: ^6.5.4
  riverpod_generator: ^1.0.6

flutter:
  uses-material-design: true
  assets:
    - assets/soccer-fans.json
    - assets/spica.png
