// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA4zazikqjFgw5PNXDtVSvUkg0DUsNsEaM',
    appId: '1:63384799682:web:bbc04fc12127e7bb3dae5b',
    messagingSenderId: '63384799682',
    projectId: 'stavnica-76806',
    authDomain: 'stavnica-76806.firebaseapp.com',
    storageBucket: 'stavnica-76806.appspot.com',
    measurementId: 'G-BVWQ90N530',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBixujxKUMceF_-k4G92kxkgUgXEi7v7io',
    appId: '1:63384799682:android:cae9b3a160b446c73dae5b',
    messagingSenderId: '63384799682',
    projectId: 'stavnica-76806',
    storageBucket: 'stavnica-76806.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBTmSQKc5ISG5-g5PLi_n9zFMg_OwnbkVI',
    appId: '1:63384799682:ios:474f40a2456e4c923dae5b',
    messagingSenderId: '63384799682',
    projectId: 'stavnica-76806',
    storageBucket: 'stavnica-76806.appspot.com',
    iosClientId: '63384799682-cj0sb5aqsdqaj7kmmqo7eros2g3vrm6i.apps.googleusercontent.com',
    iosBundleId: 'com.example.stavnica',
  );
}
